### ISSUE TITLE
Debugging from Safari Web Inspector not working

### ISSUE THREAD

**Issue by homerlex** [apache/cordova-plugin-wkwebview-engine#109]
# Bug Report

## Problem
With UIWebView I could debug from from Safari (see console outputs etc).  I just installed cordova-plugin-wkwebview-engine and now debugging from Safari (12.0.3) is not available.

### What is expected to happen?
I expected to be able to debug from Safari.

### Environment, Platform, Device
iPad Pro 9.7in
iOS 12.4

### Version information

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by homerlex** [comment]
FYI - I did a mac upgrade and now on Safari 12.1.2.  Web Inspector is now working with this plugin.

**Comment by lsc949982212** [comment]
I had the same problem

**Comment by JacopoPatroclo** [comment]
> I had the same problem

+1

**Comment by breautek** [comment]
To extend on what Homer said, you have to make sure you're using a version of Safari for Mac that is compatible with Safari for iOS to do remote debugging.

I suggest ensuring that you're mac is completely up to date (including OS upgrades). Sometimes if you're testing with the most recent iOS version, you have to use the [Safari Tech Preview](https://developer.apple.com/safari/technology-preview/) instead of the stable production version of Safari.

**Comment by burtontanner** [comment]
If you still have issues, close applications on your mac to free up memory. If that didn't work, close applications on your phone. and the last resort is to turn off bluetooth and wifi on your phone. I don't know why but it works.
