### ISSUE TITLE
Disabling the scrollbars in iOS..

### ISSUE THREAD

**Issue by spinninghamster** [apache/cordova-plugin-wkwebview-engine#114]
I tried to disable the scrollbars with:

```
::-webkit-scrollbar{
   display:none;
}
```

and it doesn't seem to be working. I found issues referencing this at:

https://issues.apache.org/jira/browse/CB-10123

But there appears to be no resolution. Is there any "quick fix" for this?

Apparently you can fix it with:

```
self.wkWebView.scrollView.showsVerticalScrollIndicator = NO;
self.wkWebView.scrollView.showsHorizontalScrollIndicator = NO;
```

But where to make these changes? Searching Google shows very few results.

**Comment by towcar** [comment]
Also struggling with this issue.

**Comment by breautek** [comment]
> Apparently you can fix it with:
```
self.wkWebView.scrollView.showsVerticalScrollIndicator = NO;
self.wkWebView.scrollView.showsHorizontalScrollIndicator = NO;
```

You can probably add that after this line
https://github.com/apache/cordova-plugin-wkwebview-engine/blob/9a8993c6830424e183ec9a76f9ad7d74fd933f6f/src/ios/CDVWKWebViewEngine.m#L99

Note that you wouldn't use `self` as in that source code, `wkWebView` is a local variable. You'll need to fork this plugin to add it. I also didn't test it and I'm unfamiliar with the code base myself, so not sure if those properties are set anywheres else.

If you feel this should be a configurable feature, I'd post a feature request on https://github.com/apache/cordova-ios (because `cordova-ios@6` makes this plugin obsolete).

If you require anymore support, our [slack](http://slack.cordova.io/) is a more appropriate place to ask questions such as this one. We generally only use GitHub for issue tracking.

**Comment by towcar** [comment]
Not sure if I need to comment now, but I was on the wrong Github page, didn't realize this was for the plugin. (Skipped using it because of cordova-io@6).

My quick fix was I made my content width 98%, and added 2% padding to allow room for the scroll bar. Worked for my iPad only app anyway.
