### ISSUE TITLE
I can't load JSON from external server CORS is enabled * 

### ISSUE THREAD

**Issue by 99electronic** [apache/cordova-plugin-wkwebview-engine#116]
I have enabled CORS on my external server and it is tested as valid CORS header, but still I can't load anything. With UIWebview there is no problem.
I tried everything, but never any load from external servers. Is there somethingI'm missing?  How should I debug those external requests to see what's wrong with the CORS or with headers? I have no idea how to debug this since it does not return any errors, it is just not working (no errors output)

**Comment by breautek** [comment]
Debugging cors problems is very difficult because by design they hide useful error messages.

You might see hints in your server logs. I've used [postman](https://www.getpostman.com/) so that I can send requests manually and see all the response details. Send the `OPTIONS` request to make sure the preflight response returns back the correct headers and content (body size should be exactly 0 bytes).

It should also provide the following http headers:
`Access-Control-Allow-Origin`
`Access-Control-Allow-Methods`
`Access-Control-Allow-Headers`

Origin should be a wildcard because you cannot reference a null origin.
Allowed methods should be a comma delimited list of http methods, e.g. `POST, GET, OPTIONS`
Allowed headers should be a comma delimited list of allowed http headers... e.g:
`Accept, Content-Type, X-Requested-With`

Here is an example of my response headers:
![CORSheaders](https://user-images.githubusercontent.com/11200662/67420205-8bc69600-f5a4-11e9-8187-7bd9e43104a4.png)

**Comment by 99electronic** [comment]
Thank you, I managed to solve this problem. In the header I needed to disable Access-Control-Allow-Credentials, that was my problem.
Thank you.
