### ISSUE TITLE
Apple still thinks I am using the UIWebView even after installing the plugin

### ISSUE THREAD

**Issue by dwinc** [apache/cordova-plugin-wkwebview-engine#148]
I installed the plugin successfully, added rules to the config.xml .. app runs just fine. Uploaded it to appstoreconnect and then still get the following email back:

**App Store Connect: Your app "xxx" (Apple ID: xxx Version: 1.1.0 Build: 1.1.0) has one or more issues**
ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 

My config has no mentioning of any other in app browser plugins.

`    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <icon src="icon.png" />
        <splash src="Default@2x~universal~anyany.png" />
        <preference name="SplashMaintainAspectRatio" value="true" />
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <icon src="icon.png" />
        <splash src="Default@2x~universal~anyany.png" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    </platform>
</widget>`

(not sure why the code is such a mess above)

Side note: I have checked if any other plugins use/refer to UIWebView .. they do not.
This is a super simple app with no other added plugins other than a native spinner.

**Comment by breautek** [comment]
At the bare minimum you need:

- `cordova-ios@5.1.1`
- a wkwebview plugin such as this one
- the [WKWebViewOnly](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html) flag 

Because you say you have no other plugins, I'll save you the spiel regarding plugins ;)

If you require anymore assistance on this issue, I invite you to our [slack](http://slack.cordova.io/). If you think you've found a bug, please do open a new issue with the form filled out.

> (not sure why the code is such a mess above)

It's because you used an inline code block instead of the multiline syntax (starts with triple backtick and ends with a triple backtick on their own lines). Examples of what I mean can be found [here](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by dwinc** [comment]
Ah 5.1.1 must be it, I noticed by just typing "cordova platform add ios" it defaults to 5.0.0...
Wonder why its not picking up a later version?
Just added it via 5.1.1, seems ok but comes with a notice "apple-ios version check failed, continuing anyways".
Will try to submit a new build and hope apple will finally accept. Thanks for the answer

**Comment by breautek** [comment]
I would assume you have 5.0.0 pinned in either your `package.json` file or maybe in your `config.xml`.

5.1.0 introduces the `WKWebViewOnly` flag, but 5.1.1, if I recall correctly, fixes a problem with that flag.
